### ISSUE TITLE
IntelliJ IDEA Community 2017.2 EAP

### ISSUE THREAD

**Issue by adoerler** [bduisenov/decompile-and-attach#10]
Hi,

this plugin sounds great, unfortunately It does not work for me.

Version 1.6 downloaded form here https://plugins.jetbrains.com/plugin/8047-decompile-and-attach cannot be installed in IntelliJ IDEA Community 2017.2 EAP.

> Plugin 'Decompile and Attach' is incompatible with this installation.

Version v1.5 from respository can be installied, but throws the following error:

`Can't find resource for bundle java.util.PropertyResourceBundle, key decompiler.use.line.table
java.util.MissingResourceException: Can't find resource for bundle java.util.PropertyResourceBundle, key decompiler.use.line.table
	at java.util.ResourceBundle.getObject(ResourceBundle.java:450)
	at java.util.ResourceBundle.getString(ResourceBundle.java:407)
	at com.intellij.openapi.util.registry.RegistryValue.getBundleValue(RegistryValue.java:171)
	at com.intellij.openapi.util.registry.RegistryValue._get(RegistryValue.java:162)
	at com.intellij.openapi.util.registry.RegistryValue.get(RegistryValue.java:142)
	at com.intellij.openapi.util.registry.RegistryValue.asBoolean(RegistryValue.java:66)
	at com.intellij.openapi.util.registry.Registry.is(Registry.java:56)
	at io.gulp.intellij.plugin.decompile.DecompileAndAttachAction$1.run(DecompileAndAttachAction.java:100)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:726)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:134)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:342)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)`

Many thanks in advance
Andreas

**Comment by dalaverd** [comment]
Could you please fix this?

Thank you

**Comment by amandeep1991** [comment]
Same with me, even I downloaded the 1.6 version separately and tried install from disk option but still it is not working.

**Comment by amandeep1991** [comment]
Please update the plugin for 2017.4 as well

**Comment by wsargent** [comment]
Same here:

Can't find resource for bundle java.util.PropertyResourceBundle, key decompiler.use.line.table

**Comment by markiewb** [comment]
Same here IU 2017.2.3. The exception is thrown when executing the action

**Comment by devendor** [comment]
I have a fix for this over in my branch for anyone watching.  I've submitted a pull request to get an official release, but I included a jar for you too. 

https://github.com/devendor/decompile-and-attach/releases

@markiewb @wsargent @amandeep1991 @dalaverd @adoerler
