### ISSUE TITLE
IDE Fatal Error

### ISSUE THREAD

**Issue by shafinmahmud** [bduisenov/decompile-and-attach#13]
Running in **IntelijIDEA 2017.2.5** Gives the Following Error when try to Decompile and Attach

```
Can't find resource for bundle java.util.PropertyResourceBundle, key decompiler.use.line.table
java.util.MissingResourceException: Can't find resource for bundle java.util.PropertyResourceBundle, key decompiler.use.line.table
	at java.util.ResourceBundle.getObject(ResourceBundle.java:450)
	at java.util.ResourceBundle.getString(ResourceBundle.java:407)
	at com.intellij.openapi.util.registry.RegistryValue.getBundleValue(RegistryValue.java:171)
	at com.intellij.openapi.util.registry.RegistryValue._get(RegistryValue.java:162)
	at com.intellij.openapi.util.registry.RegistryValue.get(RegistryValue.java:142)
	at com.intellij.openapi.util.registry.RegistryValue.asBoolean(RegistryValue.java:66)
	at com.intellij.openapi.util.registry.Registry.is(Registry.java:56)
	at io.gulp.intellij.plugin.decompile.DecompileAndAttachAction$1.run(DecompileAndAttachAction.java:100)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:718)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:548)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$2.run(ProgressManagerImpl.java:165)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:330)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by devendor** [comment]
@shafinmahmud 

I believe this is fixed in a patch I submitted.  I have an fork awaiting a pull request for inclusion in a release over here:

https://github.com/devendor/decompile-and-attach/releases

Please comment back here if you try it and it does or does not fix the issue for you.  Also, continue to track the @bduisenov branch since he's the real programmer.  I'm just helping out because I wanted it to work for me. :)

**Comment by jaimeburnap** [comment]
I get this error in 2017.3 as well

**Comment by searjeant** [comment]
Same here.

Can't find resource for bundle java.util.PropertyResourceBundle, key decompiler.use.line.table
java.util.MissingResourceException: Can't find resource for bundle java.util.PropertyResourceBundle, key decompiler.use.line.table
	at java.util.ResourceBundle.getObject(ResourceBundle.java:450)
	at java.util.ResourceBundle.getString(ResourceBundle.java:407)
	at com.intellij.openapi.util.registry.RegistryValue.getBundleValue(RegistryValue.java:171)
	at com.intellij.openapi.util.registry.RegistryValue._get(RegistryValue.java:162)
	at com.intellij.openapi.util.registry.RegistryValue.get(RegistryValue.java:142)
	at com.intellij.openapi.util.registry.RegistryValue.asBoolean(RegistryValue.java:66)
	at com.intellij.openapi.util.registry.Registry.is(Registry.java:56)
	at io.gulp.intellij.plugin.decompile.DecompileAndAttachAction$1.run(DecompileAndAttachAction.java:100)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:713)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:543)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:488)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$2.run(ProgressManagerImpl.java:165)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:315)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by teranpeterson** [comment]
Same
java.util.MissingResourceException: Can't find resource for bundle java.util.PropertyResourceBundle, key decompiler.use.line.table
	at java.base/java.util.ResourceBundle.getObject(ResourceBundle.java:564)
	at java.base/java.util.ResourceBundle.getString(ResourceBundle.java:521)
	at com.intellij.openapi.util.registry.Registry.getBundleValue(Registry.java:101)
	at com.intellij.openapi.util.registry.RegistryValue._get(RegistryValue.java:157)
	at com.intellij.openapi.util.registry.RegistryValue.get(RegistryValue.java:141)
	at com.intellij.openapi.util.registry.RegistryValue.asBoolean(RegistryValue.java:56)
	at com.intellij.openapi.util.registry.Registry.is(Registry.java:46)
	at io.gulp.intellij.plugin.decompile.DecompileAndAttachAction$1.run(DecompileAndAttachAction.java:100)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:894)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:169)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:156)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:408)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:294)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by bduisenov** [comment]
Unfortunately, this repository is not maintained any more. I could find another forked repository which might help you https://github.com/devendor/decompile-and-attach
