### ISSUE TITLE
Can't find resource for bundle java.util.PropertyResourceBundle, key decompiler.use.line.table

### ISSUE THREAD

**Issue by sergaks** [bduisenov/decompile-and-attach#7]
Hey,
when I try to decompile any jar got the exception below.

IntelliJ IDEA 2016.1.1
Build #IU-145.597, built on March 29, 2016
JRE: 1.8.0_72-b15 amd64
JVM: Java HotSpot(TM) 64-Bit Server VM by Oracle Corporation

Can't find resource for bundle java.util.PropertyResourceBundle, key decompiler.use.line.table
java.util.MissingResourceException: Can't find resource for bundle java.util.PropertyResourceBundle, key decompiler.use.line.table
    at java.util.ResourceBundle.getObject(ResourceBundle.java:450)
    at java.util.ResourceBundle.getString(ResourceBundle.java:407)
    at com.intellij.openapi.util.registry.RegistryValue.getBundleValue(RegistryValue.java:164)
    at com.intellij.openapi.util.registry.RegistryValue._get(RegistryValue.java:155)
    at com.intellij.openapi.util.registry.RegistryValue.get(RegistryValue.java:136)
    at com.intellij.openapi.util.registry.RegistryValue.asBoolean(RegistryValue.java:65)
    at com.intellij.openapi.util.registry.Registry.is(Registry.java:55)
    at io.gulp.intellij.plugin.decompile.DecompileAndAttachAction$1.run(DecompileAndAttachAction.java:100)
    at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:563)
    at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:126)
    at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:369)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

**Comment by PWAlessi** [comment]
I get the same issue.

**Comment by ghost** [comment]
The real problem is that `util.jar` (for me, it's in `C:\Program Files (x86)\JetBrains\IntelliJ IDEA Community Edition 2016.2\lib\`), in the "misc" folder, in the "registry.properties" file, there is no `decompiler.use.line.table` setting. You can hack your way around the problem by editing `registry.properties` and create the missing setting. You'll have to recreate the util.jar file and replace the original (I would recommend a backup). That got me up and running.

I believe the correct fix is to update the code to not look for that key. Most likely the key existed in earlier versions, but since removed.

**Comment by bduisenov** [comment]
Yeah, well this parameter was removed from Intellij. Unfortunately, the concept of this plugin is broken as decompiled code with line numbers is not readable and w/o them debugging would be broken. That said, the better approach would be to create a plugin providing separate window for making search through abfuscated code and opening a compiled code which would be handled by intellij.

**Comment by bduisenov** [comment]
I updated the plugin with fix

**Comment by chrisSaiki** [comment]
I am getting this issue with IntelliJ IDEA Community Edition 2017 =(

**Comment by JJonesAtAvaya** [comment]
me too

**Comment by mcsrk** [comment]
me too with IntelliJ Idea 2019.2

**Comment by vaxen** [comment]
me too with IntelliJ Idea 2019.2

**Comment by teranpeterson** [comment]
Same

**Comment by bduisenov** [comment]
Unfortunately, this repository is not maintained any more. I could find another forked repository which might help you https://github.com/devendor/decompile-and-attach
