### ISSUE TITLE
Not extracting

### ISSUE THREAD

**Issue by utrucceh** [bduisenov/decompile-and-attach#9]
Can't find resource for bundle java.util.PropertyResourceBundle, key decompiler.use.line.table
java.util.MissingResourceException: Can't find resource for bundle java.util.PropertyResourceBundle, key decompiler.use.line.table
	at java.util.ResourceBundle.getObject(ResourceBundle.java:450)
	at java.util.ResourceBundle.getString(ResourceBundle.java:407)
	at com.intellij.openapi.util.registry.RegistryValue.getBundleValue(RegistryValue.java:171)
	at com.intellij.openapi.util.registry.RegistryValue._get(RegistryValue.java:162)
	at com.intellij.openapi.util.registry.RegistryValue.get(RegistryValue.java:142)
	at com.intellij.openapi.util.registry.RegistryValue.asBoolean(RegistryValue.java:66)
	at com.intellij.openapi.util.registry.Registry.is(Registry.java:56)
	at io.gulp.intellij.plugin.decompile.DecompileAndAttachAction$1.run(DecompileAndAttachAction.java:100)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:726)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:137)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:334)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by huzongyao** [comment]
find the same error

**Comment by devendor** [comment]
@huzongyao @utrucceh 
If you using 2017.x, I have an fork awaiting a pull request for inclusion in a release over here:

https://github.com/devendor/decompile-and-attach/releases

Please comment back here if you try it and it does or does not fix the issue for you so the maintainer gets details.
